import imp
from   io                   import StringIO
from   pluggdapps.plugin    import Plugin, implements
import pluggdapps.utils     as h
from   tayra                import BaseTTLPlugin

__compiler = _compiler()
ttlcode = __compiler.compilettl( file='/home/pratap/dev/tayra/tayra/test/stdttl/element.ttl' )
_context = globals()['_context']
_context['_compiler'] = __compiler
_context['this'] = this
blocks = __compiler.load( ttlcode, context=_context )


def body( *args, **kwargs ) :  
  _m.pushbuf()
  _m.pushbuf()
  _m.extend( ['<html>'] )
  _m.pushbuf()
  _m.extend( ['\n  '] )
  _m.pushbuf()
  _m.extend( ['<head .pluggdsite>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<link image/ico "'] )
  _m.append(_m.evalexprs( 'favicon', '', globals(), locals()) )
  _m.extend( ['" rel="icon">'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.extend( [''] )
  _m.append(_m.evalexprs( 'this.hd_title()', '', globals(), locals()) )
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.hd_meta()', '', globals(), locals()) )
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.hd_links()', '', globals(), locals()) )
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.hd_styles()', '', globals(), locals()) )
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.hd_script()', '', globals(), locals()) )
  _m.extend( ['\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<body .pluggdsite>'] )
  _m.pushbuf()
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.bd_header()', '', globals(), locals()) )
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.bd_body()', '', globals(), locals()) )
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.bd_footer()', '', globals(), locals()) )
  _m.extend( ['\n\n\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()

# ---- Global Functions
favicon = 'static/paicon16x16.png'
title = 'base-page'

def hd_title() :  
  _m.pushbuf()
  _m.pushbuf()
  _m.extend( ['<title>'] )
  _m.pushbuf()
  _m.extend( [' '] )
  _m.append(_m.evalexprs( 'title', '', globals(), locals()) )
  _m.extend( ['\n\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()


def hd_meta() :  
  _m.pushbuf()
  pass
  return _m.popbuftext()


def hd_links() :  
  _m.pushbuf()
  fnt_amaranth = 'static/fonts/amaranth/Amaranth-webfont.woff'
  fnt_opensans = 'static/fonts/open_sans/OpenSans-Regular-webfont.woff'
  
  _m.pushbuf()
  _m.extend( ['<style text/css>'] )
  _m.pushbuf()
  _m.extend( ['\n    ', '@font-face {', '\n      ', "font-family: 'Amaranth';", '\n      ', 'font-style: normal;', '\n      ', 'font-weight: normal;', '\n      ', "src: local('Amaranth'), url('"] )
  _m.append(_m.evalexprs( 'fnt_amaranth', '', globals(), locals()) )
  _m.extend( ["') format('woff');", '\n    ', '}', '\n    ', '@font-face {', '\n      ', "font-family: 'Open Sans';", '\n      ', 'font-style: normal;', '\n      ', 'font-weight: normal;', '\n      ', "src: local('Open Sans'), url('"] )
  _m.append(_m.evalexprs( 'fnt_opensans', '', globals(), locals()) )
  _m.extend( ["') format('woff');", '\n    ', '}', '\n\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  defaultcss = 'static/default.css'
  _m.pushbuf()
  _m.extend( ['<link text/css "'] )
  _m.append(_m.evalexprs( 'defaultcss', '', globals(), locals()) )
  _m.extend( ['" rel="stylesheet" charset="utf-8">'] )
  _m.pushbuf()
  _m.extend( ['\n    \n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()


def hd_styles() :  
  _m.pushbuf()
  pass
  return _m.popbuftext()


def hd_script() :  
  _m.pushbuf()
  jqueryfile = 'static/jquery-1.5.1.min.js'
  jqlibfile = 'static/jqlib.js'
  _m.pushbuf()
  _m.extend( ['<script text/javascript "'] )
  _m.append(_m.evalexprs( 'jqueryfile', '', globals(), locals()) )
  _m.extend( ['">'] )
  _m.pushbuf()
  _m.extend( ['\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<script text/javascript "'] )
  _m.append(_m.evalexprs( 'jqlibfile', '', globals(), locals()) )
  _m.extend( ['">'] )
  _m.pushbuf()
  _m.extend( ['\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<script type="text/javascript">'] )
  _m.pushbuf()
  _m.extend( ['\n    ', 'var _gaq = _gaq || [];', '\n    ', "_gaq.push(['_setAccount', 'UA-26824958-1']);", '\n    ', "_gaq.push(['_setDomainName', 'pluggdapps.com']);", '\n    ', "_gaq.push(['_trackPageview']);", '\n    ', '(function() {', '\n      ', "var ga = document.createElement('script');", '\n      ', "ga.type = 'text/javascript'; ga.async = true;", '\n      ', "ga.src = ('https:' == document.location.protocol ?", '\n                  ', "'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';", '\n      ', "var s = document.getElementsByTagName('script')[0];", '\n      ', 's.parentNode.insertBefore(ga, s);', '\n    ', '})();', '\n\n\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()


def bd_header() :  
  _m.pushbuf()
  pass
  return _m.popbuftext()


def bd_body() :  
  _m.pushbuf()
  _m.pushbuf()
  _m.extend( ['<div #right>'] )
  _m.pushbuf()
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.body_rightpane()', '', globals(), locals()) )
  _m.extend( ['\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<div #left>'] )
  _m.pushbuf()
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.body_leftpane()', '', globals(), locals()) )
  _m.extend( ['\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<div #center>'] )
  _m.pushbuf()
  _m.extend( ['\n    ', ''] )
  _m.append(_m.evalexprs( 'this.body_centerpane()', '', globals(), locals()) )
  _m.extend( ['\n\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()


def body_leftpane() :  
  _m.pushbuf()
  _m.pushbuf()
  _m.extend( ['<div .ralign.leftpane>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<ul>'] )
  _m.pushbuf()
  _m.extend( ['\n      '] )
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "/index">'] )
  _m.pushbuf()
  _m.extend( [' home', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "/overview">'] )
  _m.pushbuf()
  _m.extend( [' bootstrap', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "/ispecroot">'] )
  _m.pushbuf()
  _m.extend( [' Interface Specification Request', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "/config">'] )
  _m.pushbuf()
  _m.extend( [' Configuration', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "/psite_getstarted">'] )
  _m.pushbuf()
  _m.extend( [' Get Started', '\n\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()


def body_centerpane() :  
  _m.pushbuf()
  pass
  return _m.popbuftext()


def body_rightpane() :  
  _m.pushbuf()
  _m.pushbuf()
  _m.extend( ['<nav {font-size : x-large}>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<a .fntbold "/googlegroup">'] )
  _m.pushbuf()
  _m.extend( [' Join', '\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<br/>'] )
  _m.pushbuf()
  _m.extend( ['\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<div .builton>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<b>'] )
  _m.pushbuf()
  _m.extend( [' built-on ', '\n    '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<ul>'] )
  _m.pushbuf()
  _m.extend( ['\n      '] )
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://whatwg.org">'] )
  _m.pushbuf()
  _m.extend( [' HTML5', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://python.org">'] )
  _m.pushbuf()
  _m.extend( [' python', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "https://developer.mozilla.org/en/JavaScript_Language_Resources">'] )
  _m.pushbuf()
  _m.extend( [' JavaScript', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://erlang.org">'] )
  _m.pushbuf()
  _m.extend( [' Erlang', '\n\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<div .builtwith>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<b>'] )
  _m.pushbuf()
  _m.extend( [' built-with ', '\n    '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<ul>'] )
  _m.pushbuf()
  _m.extend( ['\n      '] )
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://pylonsproject.com">'] )
  _m.pushbuf()
  _m.extend( [' Pyramid', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://eazytext.pluggdapps.com">'] )
  _m.pushbuf()
  _m.extend( [' EazyText', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://tayra.pluggdapps.com">'] )
  _m.pushbuf()
  _m.extend( [' Tayra', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://couchdb.org">'] )
  _m.pushbuf()
  _m.extend( [' CouchDB', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://couchpy.pluggdapps.com">'] )
  _m.pushbuf()
  _m.extend( [' CouchPy', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://jquery.com/">'] )
  _m.pushbuf()
  _m.extend( [' jQuery', '\n\n  '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<div .builtfor>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<b>'] )
  _m.pushbuf()
  _m.extend( [' built-for ', '\n    '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<ul>'] )
  _m.pushbuf()
  _m.extend( ['\n      '] )
  _m.pushbuf()
  _m.extend( ['<li>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.pushbuf()
  _m.extend( ['<a "http://pluggdapps.com">'] )
  _m.pushbuf()
  _m.extend( [' pluggdapps.com', '\n\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()


def bd_footer() :  
  _m.pushbuf()
  _m.pushbuf()
  _m.extend( ['<table #footer>'] )
  _m.pushbuf()
  _m.extend( ['\n    '] )
  _m.pushbuf()
  _m.extend( ['<tr>'] )
  _m.pushbuf()
  _m.extend( ['\n      '] )
  _m.pushbuf()
  _m.extend( ['<td .copyright>'] )
  _m.pushbuf()
  _m.extend( ['\n        ', 'An SKR Farms Initiative.', '\n        '] )
  _m.pushbuf()
  _m.extend( ['<br/>'] )
  _m.pushbuf()
  _m.extend( ['\n        '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.extend( ['Website content copyright © by SKR Farms. All rights reserved.', '\n        ', 'Pluggdapps and its documentation are licensed under "GPL Version-3".', '\n      '] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.pushbuf()
  _m.extend( ['<td .papowered>'] )
  _m.pushbuf()
  _m.extend( ['\n        ', ''] )
  _m.append(_m.evalexprs( 'blocks.papowered( 100, 10 )', '', globals(), locals()) )
  _m.extend( ['\n'] )
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  _m.handletag( _m.popbuftext(), _m.popbuftext(), indent=False, nl='')
  return _m.popbuftext()

# ---- Interface functions

# ---- Footer
_ttlhash = ''
_ttlfile = '/home/pratap/dev/tayra/tayra/test/stdttl/base.ttl' 